name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/brahmitarek6/learning.git"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "brahmitarek6"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "33168703"
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}